spring.application.name=universidad
server.address=0.0.0.0
server.port=4001

spring.datasource.url=jdbc:postgresql://localhost:5432/asignaciones
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.data.redis.port=6379
spring.data.redis.host=redis
#spring.jpa.properties.hibernate.default_schema=asignaciones